# Configuration de Shiny Server pour Render

server {
  listen 3838;

  # Application Shiny
  location / {
    app_dir /srv/shiny-server;

    log_dir /var/log/shiny-server;

    directory_index on;

    # Autoriser les connexions WebSocket
    websocket_keepalive true;
  }
}

